services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"
    env_file:
      - .env

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db/todo.sql:/docker-entrypoint-initdb.d/todo.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"

volumes:
  db_data:

